#!/usr/bin/env python3
"""Build the deterministic embedded A1099 recovery `.pocket` package.

The format authority is contracts/spec/pocket-package.ts. This script emits a
single `ipod-photo` variant and an aligned C byte array, then parses and hashes
the result again before returning success.
"""
from __future__ import annotations

import argparse
import struct
from pathlib import Path

MAGIC = 0x544B4350
VERSION = 1
ALIGN = 16
HEADER_SIZE = 16
VARIANT_SIZE = 40
SECTION_SIZE = 16
TARGET_BYTES = 16
TARGET = "ipod-photo"
HOST_ABI = 1

SECTION_IDENTITY = 1
SECTION_PLAN = 2
SECTION_JS = 3

FNV_OFFSET = 0xCBF29CE484222325
FNV_PRIME = 0x100000001B3
FNV_MASK = 0xFFFFFFFFFFFFFFFF


def align(value: int) -> int:
    return (value + ALIGN - 1) & ~(ALIGN - 1)


def fnv1a64(*chunks: bytes) -> int:
    value = FNV_OFFSET
    for chunk in chunks:
        for byte in chunk:
            value ^= byte
            value = (value * FNV_PRIME) & FNV_MASK
    return value


def verify_container(package: bytes) -> bytes:
    if len(package) < HEADER_SIZE + VARIANT_SIZE + 8:
        raise ValueError("package is truncated")
    magic, version, manifest_len, variants = struct.unpack_from("<4I", package, 0)
    if (magic, version, variants) != (MAGIC, VERSION, 1):
        raise ValueError("package header mismatch")
    if struct.unpack_from("<Q", package, len(package) - 8)[0] != fnv1a64(package[:-8]):
        raise ValueError("package footer hash mismatch")
    variant = align(HEADER_SIZE + manifest_len)
    if variant + VARIANT_SIZE > len(package) - 8:
        raise ValueError("package variant is truncated")
    raw_target = package[variant : variant + TARGET_BYTES].split(b"\0", 1)[0].decode("utf-8")
    host_abi, section_count, section_table = struct.unpack_from("<3I", package, variant + 16)
    if raw_target != TARGET or host_abi != HOST_ABI or section_count == 0:
        raise ValueError("package variant mismatch")
    if section_table + section_count * SECTION_SIZE > len(package) - 8:
        raise ValueError("package section table is truncated")
    payloads: list[bytes] = []
    javascript = None
    for index in range(section_count):
        kind, _reserved, offset, length = struct.unpack_from(
            "<4I", package, section_table + index * SECTION_SIZE
        )
        payload = package[offset : offset + length]
        if len(payload) != length:
            raise ValueError("package section is truncated")
        payloads.append(payload)
        if kind == SECTION_JS:
            javascript = payload
    if struct.unpack_from("<Q", package, variant + 32)[0] != fnv1a64(*payloads):
        raise ValueError("variant hash mismatch")
    if javascript is None or len(javascript) < 2 or javascript[-1] != 0:
        raise ValueError("package JavaScript is missing or not NUL-terminated")
    return javascript


def emit_c(package: bytes, output: Path, launcher_hash: int = 0) -> None:
    lines = [
        "/* Generated by tools/build_embedded_pocket.py; do not edit. */",
        "#include <stdint.h>",
        "",
        "const uint8_t pjs_embedded_package[]",
        "    __attribute__((aligned(16), section(\".rodata.pjs_package\"))) = {",
    ]
    for offset in range(0, len(package), 12):
        chunk = package[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    lines += [
        "};",
        f"const uint32_t pjs_embedded_package_length = {len(package)}u;",
        f"const uint32_t pjs_launcher_hash_low = 0x{launcher_hash & 0xffffffff:08x}u;",
        f"const uint32_t pjs_launcher_hash_high = 0x{launcher_hash >> 32:08x}u;",
        "",
    ]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-package", type=Path, required=True)
    parser.add_argument("--package", type=Path, required=True)
    parser.add_argument("--c-output", type=Path, required=True)
    parser.add_argument("--launcher-package", type=Path)
    args = parser.parse_args()

    package = args.input_package.read_bytes()
    verify_container(package)
    args.package.parent.mkdir(parents=True, exist_ok=True)
    args.package.write_bytes(package)
    launcher_hash = 0
    if args.launcher_package is not None:
        launcher = args.launcher_package.read_bytes()
        verify_container(launcher)
        launcher_hash = fnv1a64(launcher[:-8])
    emit_c(package, args.c_output, launcher_hash)
    print(f"embedded package: {len(package)} bytes, FNV-1a64 0x{fnv1a64(package[:-8]):016x}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
